{"name": "部门小组信息更新", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'fail' == 'pass'\n  - fail\n  + pass", "trace": "self = <test_case.test_excel.TestExcel object at 0x000002318E0EEE80>\nresult = {'data': {'id': 10010, 'name': '123'}, 'method': 'post', 'res': <Response [200]>, 'result': 'fail', ...}\n\n    @allure.severity(allure.severity_level.CRITICAL)  # 发生BUG时的严重程度\n    @pytest.mark.parametrize(\"result\", results)\n    def test_excel(self, result):\n        allure.dynamic.title(str(result['title']))\n        allure.dynamic.description(f\"{str(result['method'])} {str(result['url'])}\")\n        with allure.step(f\"method:{str(result['method'])}\"):\n            pass\n        with allure.step(f\"url:{str(result['url'])}\"):\n            pass\n        with allure.step(f\"data:{str(result['data'])}\"):\n            pass\n        with allure.step(f\"res:{str(result['res'].json())}\"):\n            pass\n        with allure.step(f\"响应时间:{str(result['res'].elapsed.total_seconds())}s\"):\n            pass\n>       assert result[\"result\"] == \"pass\"\nE       AssertionError: assert 'fail' == 'pass'\nE         - fail\nE         + pass\n\ntest_case\\test_excel.py:38: AssertionError"}, "description": "post https://192.168.1.205/api/auth/department/update", "steps": [{"name": "method:post", "status": "passed", "start": 1610505757857, "stop": 1610505757857}, {"name": "url:https://192.168.1.205/api/auth/department/update", "status": "passed", "start": 1610505757857, "stop": 1610505757857}, {"name": "data:{'id': 10010, 'name': '123'}", "status": "passed", "start": 1610505757857, "stop": 1610505757857}, {"name": "res:{'code': 1, 'message': 'CmdbUserDepartmentNotExist', 'data': {}}", "status": "passed", "start": 1610505757857, "stop": 1610505757857}, {"name": "响应时间:0.035642s", "status": "passed", "start": 1610505757857, "stop": 1610505757857}], "parameters": [{"name": "result", "value": "{'title': '部门小组信息更新', 'method': 'post', 'url': 'https://192.168.1.205/api/auth/department/update', 'data': {'id': 10010, 'name': '123'}, 'result': 'fail', 'res': <Response [200]>}"}], "start": 1610505757857, "stop": 1610505757857, "uuid": "e9470a6b-14b0-4607-958c-203f035cc6b4", "historyId": "ea1eabd553c29d1d0fe0b4fb9ac23ea8", "testCaseId": "c702837ae51103cc760768369bdfeabd", "fullName": "test_case.test_excel.TestExcel#test_excel", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_excel"}, {"name": "subSuite", "value": "TestExcel"}, {"name": "host", "value": "DESKTOP-T3GOI97"}, {"name": "thread", "value": "1036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_excel"}]}